# Set all versions
CUSTOM_BUILD_TYPE ?= Unofficial

CUSTOM_CERBERUS_VERSION := 2.0
CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY)UTC' +%s)
CUSTOM_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)

CUSTOM_PLATFORM_VERSION := Ten

TARGET_PRODUCT_SHORT := $(subst aosp_,,$(CUSTOM_BUILD))

//CUSTOM_VERSION := Cerberus_$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-BETA-$(CUSTOM_BUILD_TYPE)
CUSTOM_VERSION := CerberusOS-v$(CUSTOM_CERBERUS_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_PLATFORM_VERSION)4$(CUSTOM_BUILD)-$(CUSTOM_BUILD_TYPE)
CUSTOM_VERSION_PROP := 10
ROM_FINGERPRINT := Cerberus/$(CUSTOM_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CUSTOM_BUILD_DATE)

CUSTOM_PROPERTIES := \
    org.cerberus.version=$(CUSTOM_VERSION_PROP) \
    org.cerberus.version.display=$(CUSTOM_VERSION) \
    org.cerberus.build_date=$(CUSTOM_BUILD_DATE) \
    org.cerberus.build_date_utc=$(CUSTOM_BUILD_DATE_UTC) \
    org.cerberus.build_type=$(CUSTOM_BUILD_TYPE) \
    org.cerberus.fingerprint=$(ROM_FINGERPRINT)
